distributable:
  url: git+https://github.com/cowsay-org/cowsay.git
  ref: ${{version.tag}}

display-name: cowsay

versions:
  github: cowsay-org/cowsay

platforms:
  - darwin
  - linux/x86-64

build:
  script:
    - run: cpan File::Find
      if: linux
    - make install prefix={{prefix}}

provides:
  - cowsay

test:
  dependencies:
    github.com/cowsay-org/cowsay: '*'
  script:
    cowsay "hi"

