distributable:
  url: https://github.com/cowsay-org/cowsay/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

display-name: cowsay

versions:
  github: cowsay-org/cowsay

dependencies:
  cpanmin.us: '*'

build:
  script:
    - run: cpanm -l {{prefix}} File::Find
      if: linux
    - make install prefix={{prefix}}

provides:
  - bin/cowsay

test:
  script:
    cowsay "hi"

